"""
MIS 542: Spam Detection Project
app.py — Streamlit interface only

Requirements:
    - model.pkl    (generated by train_model.py)
    - results.pkl  (generated by train_model.py)

Run:
    streamlit run app.py
"""

import re
import pickle
import numpy as np
import streamlit as st
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

# ─────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="MIS 542 — Spam Detector",
    page_icon="🛡️",
    layout="wide",
)

# ─────────────────────────────────────────────
# CUSTOM CSS
# ─────────────────────────────────────────────
st.markdown("""
<style>
    /* Result boxes */
    .spam-box {
        background-color: #fff0f0;
        border-left: 6px solid #e53935;
        padding: 18px 22px;
        border-radius: 8px;
        margin-top: 14px;
    }
    .valid-box {
        background-color: #f0fff4;
        border-left: 6px solid #43a047;
        padding: 18px 22px;
        border-radius: 8px;
        margin-top: 14px;
    }
    .spam-title  { color: #b71c1c; font-size: 24px; font-weight: 700; margin-bottom: 4px; }
    .valid-title { color: #1b5e20; font-size: 24px; font-weight: 700; margin-bottom: 4px; }
    .conf-text   { color: #444;    font-size: 15px; }

    /* Metric cards */
    div[data-testid="metric-container"] {
        background: #f8f9fa;
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 10px 14px;
    }
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────
# PREPROCESSING  (same function as train_model.py)
# ─────────────────────────────────────────────
def preprocess(text: str) -> str:
    """
    Applies all 6 cleaning steps:
      i.   Lowercase
      ii.  Remove special characters
      iii. Remove stop words
      iv.  Remove hyperlinks
      v.   Remove numbers
      vi.  Remove extra whitespace
    """
    text = str(text)
    # i. Lowercase
    text = text.lower()
    # iv. Hyperlinks
    text = re.sub(r'http\S+|www\.\S+', '', text)
    # v. Numbers
    text = re.sub(r'\d+', '', text)
    # ii. Special characters
    text = re.sub(r'[^a-z\s]', '', text)
    # vi. Whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # iii. Stop words
    tokens = [t for t in text.split()
              if t not in ENGLISH_STOP_WORDS and len(t) > 1]
    return ' '.join(tokens)


# ─────────────────────────────────────────────
# LOAD MODEL & RESULTS
# ─────────────────────────────────────────────
@st.cache_resource
def load_artifacts():
    with open('model.pkl', 'rb') as f:
        model_data = pickle.load(f)
    with open('results.pkl', 'rb') as f:
        results = pickle.load(f)
    return model_data, results

try:
    model_data, results = load_artifacts()
    vectorizer  = model_data['vectorizer']
    model       = model_data['model']
    use_abs     = model_data['use_abs']
    best_name   = model_data['best_name']
    loaded_ok   = True
except FileNotFoundError:
    loaded_ok = False


# ─────────────────────────────────────────────
# SIDEBAR — Model Performance
# ─────────────────────────────────────────────
with st.sidebar:
    st.title("📊 Model Performance")
    st.caption("Evaluated on 20 % hold-out test set  (1,115 messages)")

    if loaded_ok:
        short = {
            'KNN  (K-Nearest Neighbors)':  'KNN',
            'NB   (Naive Bayes)':          'Naive Bayes',
            'LR   (Logistic Regression)':  'Logistic Regression',
            'DT   (Decision Tree)':        'Decision Tree',
        }

        tab_before, tab_after = st.tabs(["Before SMOTE", "After SMOTE ✅"])

        with tab_before:
            for full, short_name in short.items():
                m = results['before'][full]
                st.markdown(f"**{short_name}**")
                c1, c2, c3 = st.columns(3)
                c1.metric("Acc",   f"{m['acc']*100:.1f}%")
                c2.metric("Recall",f"{m['recall']*100:.1f}%")
                c3.metric("F1",    f"{m['f1']*100:.1f}%")
                st.divider()

        with tab_after:
            for full, short_name in short.items():
                m = results['after'][full]
                st.markdown(f"**{short_name}**")
                c1, c2, c3 = st.columns(3)
                c1.metric("Acc",   f"{m['acc']*100:.1f}%")
                c2.metric("Recall",f"{m['recall']*100:.1f}%")
                c3.metric("F1",    f"{m['f1']*100:.1f}%")
                st.divider()

        st.info(f"🏆 **Active model:** {best_name.strip()}  \n(Best accuracy after SMOTE)")
    else:
        st.warning("Run `train_model.py` first to generate model.pkl")

    st.caption("MIS 542 · Semester 252 · 2026")


# ─────────────────────────────────────────────
# MAIN PAGE
# ─────────────────────────────────────────────
st.title("🛡️ Email Spam Detector")
st.markdown(
    "Type or paste any email / SMS message below. "
    "The model will instantly tell you whether it is **spam** or **valid**."
)
st.divider()

if not loaded_ok:
    st.error(
        "⚠️ `model.pkl` or `results.pkl` not found.  \n"
        "Please run `python train_model.py` first, then restart the app."
    )
    st.stop()

# ── Example messages ──────────────────────────
EXAMPLES = {
    "🏆 Prize winner  (spam)":
        "Congratulations! You have won a 1000 prize reward! "
        "To claim call 09061701461 now. T&C apply. Reply STOP to cancel.",
    "📅 Meeting request  (valid)":
        "Hi, are you joining the team meeting tomorrow at 10am? "
        "I will send you the Zoom link if you need it.",
    "💊 Free medication  (spam)":
        "FREE Guaranteed entry! Text WIN to 83600 to claim your "
        "free medication samples worth 500.",
    "🍕 Dinner reminder  (valid)":
        "I am running a bit late tonight. Can you please save some dinner "
        "for me? I will be home by 8.",
    "💳 Bank urgent alert  (spam)":
        "URGENT: Your bank account has been compromised. Click here "
        "immediately to verify your details and protect your funds.",
    "📚 Study group  (valid)":
        "Hey, we are forming a study group for the MIS 542 final exam. "
        "Are you in? We are meeting at the library on Thursday.",
}

st.subheader("Try an example")
cols = st.columns(3)
selected = None
for i, (label, msg) in enumerate(EXAMPLES.items()):
    if cols[i % 3].button(label, use_container_width=True):
        selected = msg

# ── Text area ────────────────────────────────
st.subheader("Or enter your own message")
user_input = st.text_area(
    label="message",
    value=selected or "",
    height=150,
    placeholder="Paste or type an email / SMS message here…",
    label_visibility="collapsed",
)

classify_btn = st.button("🔍  Classify", type="primary", use_container_width=True)

# ── Classification ────────────────────────────
if classify_btn:
    msg = user_input.strip()
    if not msg:
        st.warning("Please enter a message before classifying.")
    else:
        # Preprocess → vectorize → predict
        cleaned = preprocess(msg)
        vec     = vectorizer.transform([cleaned])
        if use_abs:
            vec = np.abs(vec.toarray())

        prediction  = model.predict(vec)[0]
        probs       = model.predict_proba(vec)[0]
        spam_prob   = float(probs[1])
        valid_prob  = float(probs[0])
        is_spam     = prediction == 1

        st.divider()

        # Result card
        if is_spam:
            st.markdown(f"""
            <div class="spam-box">
                <div class="spam-title">🚨 SPAM</div>
                <div class="conf-text">Confidence: <strong>{spam_prob*100:.1f}%</strong> spam probability</div>
            </div>""", unsafe_allow_html=True)
        else:
            st.markdown(f"""
            <div class="valid-box">
                <div class="valid-title">✅ VALID</div>
                <div class="conf-text">Confidence: <strong>{valid_prob*100:.1f}%</strong> valid probability</div>
            </div>""", unsafe_allow_html=True)

        # Probability bars
        st.markdown("#### Probability breakdown")
        col1, col2 = st.columns(2)
        col1.metric("✅ Valid", f"{valid_prob*100:.1f}%")
        col2.metric("🚨 Spam",  f"{spam_prob*100:.1f}%")

        st.progress(
            spam_prob,
            text=f"Spam likelihood  →  {spam_prob*100:.1f}%"
        )

        # Show cleaned tokens
        with st.expander("🔬 View preprocessed tokens"):
            st.code(
                cleaned if cleaned else "(all words were filtered out)",
                language=None
            )

        # How it works
        st.info(
            "**How it works:** Your message goes through a 6-step cleaning pipeline "
            "(lowercase → remove links → remove numbers → remove special characters → "
            "remove whitespace → remove stop words), then converted to a TF-IDF vector. "
            f"The **{best_name.strip()}** model (trained on 5,572 labelled messages, "
            "balanced with SMOTE) produces the classification above."
        )
